/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GradingCalculator;

/**
 *
 * @author paras
 */
public class GradingCalculator extends javax.swing.JFrame {

    /**
     * Creates new form GradingCalculator
     */
    public GradingCalculator() {
        initComponents();
    }
    String op = null;
    int num1, num2, num3, num4, num5, num6, num7;//Initializes num1 to num7 as integer values.

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jtxtaps11 = new javax.swing.JTextField();
        jtxtn1 = new javax.swing.JTextField();
        jtxtN1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jtxtn2 = new javax.swing.JTextField();
        jtxtN2 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jtxtn3 = new javax.swing.JTextField();
        jtxtN3 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jtxtn4 = new javax.swing.JTextField();
        jtxtN4 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jtxtn5 = new javax.swing.JTextField();
        jtxtN5 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox<>();
        jtxtn6 = new javax.swing.JTextField();
        jtxtN6 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox<>();
        jtxtn7 = new javax.swing.JTextField();
        jtxtN7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jtxtaps10 = new javax.swing.JTextField();
        jtxtaps13 = new javax.swing.JTextField();
        jtxtaps12 = new javax.swing.JTextField();
        jtxtaps14 = new javax.swing.JTextField();
        jtxtaps16 = new javax.swing.JTextField();
        jtxtaps15 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jtxttotal = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empty", "Afrikaans First Additional Language", "Afrikaans Home Language", "Agricultural Sciences", "Accounting", "Business Studies", "Computer Applications Technology", "Economics", "English First Additional Language", "English Home Language", "Geography", "History", "Information Technology", "IsiNdebele First Additional Language", "IsiNdebele Home Language", "IsiXhosa First Additional Language", "IsiXhosa Home Language", "IsiZulu First Additional Language", "IsiZulu Home Language", "Life Orientation", "Life Sciences", "Mathematical Literacy", "Mathematics", "Physical Sciences", "Religion Studies", "Sepedi First Additional Language", "Sepedi Home Language", "Sesotho First Additional Language", "Sesotho Home Language", "Setswana First Additional Language", "Setswana Home Language", "SiSwati First Additional Language", "SiSwati Home Language", "Tshivenda First Additional Language", "Tshivenda Home Language", "Xitsonga First Additional Language", "Xitsonga Home Language" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 650, 60));

        jtxtaps11.setEditable(false);
        jtxtaps11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtaps11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 310, 190, 60));

        jtxtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 190, 60));

        jtxtN1.setEditable(false);
        jtxtN1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, 190, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Grade");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 170, 130, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("APS Points");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 170, 190, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Mark");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 130, 50));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empty", "Afrikaans First Additional Language", "Afrikaans Home Language", "Agricultural Sciences", "Accounting", "Business Studies", "Computer Applications Technology", "Economics", "English First Additional Language", "English Home Language", "Geography", "History", "Information Technology", "IsiNdebele First Additional Language", "IsiNdebele Home Language", "IsiXhosa First Additional Language", "IsiXhosa Home Language", "IsiZulu First Additional Language", "IsiZulu Home Language", "Life Orientation", "Life Sciences", "Mathematical Literacy", "Mathematics", "Physical Sciences", "Religion Studies", "Sepedi First Additional Language", "Sepedi Home Language", "Sesotho First Additional Language", "Sesotho Home Language", "Setswana First Additional Language", "Setswana Home Language", "SiSwati First Additional Language", "SiSwati Home Language", "Tshivenda First Additional Language", "Tshivenda Home Language", "Xitsonga First Additional Language", "Xitsonga Home Language" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 650, 60));

        jtxtn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 190, 60));

        jtxtN2.setEditable(false);
        jtxtN2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtN2ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, 190, 60));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empty", "Afrikaans First Additional Language", "Afrikaans Home Language", "Agricultural Sciences", "Accounting", "Business Studies", "Computer Applications Technology", "Economics", "English First Additional Language", "English Home Language", "Geography", "History", "Information Technology", "IsiNdebele First Additional Language", "IsiNdebele Home Language", "IsiXhosa First Additional Language", "IsiXhosa Home Language", "IsiZulu First Additional Language", "IsiZulu Home Language", "Life Orientation", "Life Sciences", "Mathematical Literacy", "Mathematics", "Physical Sciences", "Religion Studies", "Sepedi First Additional Language", "Sepedi Home Language", "Sesotho First Additional Language", "Sesotho Home Language", "Setswana First Additional Language", "Setswana Home Language", "SiSwati First Additional Language", "SiSwati Home Language", "Tshivenda First Additional Language", "Tshivenda Home Language", "Xitsonga First Additional Language", "Xitsonga Home Language" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 650, 60));

        jtxtn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 190, 60));

        jtxtN3.setEditable(false);
        jtxtN3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 390, 190, 60));

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empty", "Afrikaans First Additional Language", "Afrikaans Home Language", "Agricultural Sciences", "Accounting", "Business Studies", "Computer Applications Technology", "Economics", "English First Additional Language", "English Home Language", "Geography", "History", "Information Technology", "IsiNdebele First Additional Language", "IsiNdebele Home Language", "IsiXhosa First Additional Language", "IsiXhosa Home Language", "IsiZulu First Additional Language", "IsiZulu Home Language", "Life Orientation", "Life Sciences", "Mathematical Literacy", "Mathematics", "Physical Sciences", "Religion Studies", "Sepedi First Additional Language", "Sepedi Home Language", "Sesotho First Additional Language", "Sesotho Home Language", "Setswana First Additional Language", "Setswana Home Language", "SiSwati First Additional Language", "SiSwati Home Language", "Tshivenda First Additional Language", "Tshivenda Home Language", "Xitsonga First Additional Language", "Xitsonga Home Language" }));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 650, 60));

        jtxtn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 190, 60));

        jtxtN4.setEditable(false);
        jtxtN4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 470, 190, 60));

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empty", "Afrikaans First Additional Language", "Afrikaans Home Language", "Agricultural Sciences", "Accounting", "Business Studies", "Computer Applications Technology", "Economics", "English First Additional Language", "English Home Language", "Geography", "History", "Information Technology", "IsiNdebele First Additional Language", "IsiNdebele Home Language", "IsiXhosa First Additional Language", "IsiXhosa Home Language", "IsiZulu First Additional Language", "IsiZulu Home Language", "Life Orientation", "Life Sciences", "Mathematical Literacy", "Mathematics", "Physical Sciences", "Religion Studies", "Sepedi First Additional Language", "Sepedi Home Language", "Sesotho First Additional Language", "Sesotho Home Language", "Setswana First Additional Language", "Setswana Home Language", "SiSwati First Additional Language", "SiSwati Home Language", "Tshivenda First Additional Language", "Tshivenda Home Language", "Xitsonga First Additional Language", "Xitsonga Home Language" }));
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 650, 60));

        jtxtn5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 190, 60));

        jtxtN5.setEditable(false);
        jtxtN5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, 190, 60));

        jComboBox6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empty", "Afrikaans First Additional Language", "Afrikaans Home Language", "Agricultural Sciences", "Accounting", "Business Studies", "Computer Applications Technology", "Economics", "English First Additional Language", "English Home Language", "Geography", "History", "Information Technology", "IsiNdebele First Additional Language", "IsiNdebele Home Language", "IsiXhosa First Additional Language", "IsiXhosa Home Language", "IsiZulu First Additional Language", "IsiZulu Home Language", "Life Orientation", "Life Sciences", "Mathematical Literacy", "Mathematics", "Physical Sciences", "Religion Studies", "Sepedi First Additional Language", "Sepedi Home Language", "Sesotho First Additional Language", "Sesotho Home Language", "Setswana First Additional Language", "Setswana Home Language", "SiSwati First Additional Language", "SiSwati Home Language", "Tshivenda First Additional Language", "Tshivenda Home Language", "Xitsonga First Additional Language", "Xitsonga Home Language" }));
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 650, 60));

        jtxtn6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 630, 190, 60));

        jtxtN6.setEditable(false);
        jtxtN6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 630, 190, 60));

        jComboBox7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empty", "Afrikaans First Additional Language", "Afrikaans Home Language", "Agricultural Sciences", "Accounting", "Business Studies", "Computer Applications Technology", "Economics", "English First Additional Language", "English Home Language", "Geography", "History", "Information Technology", "IsiNdebele First Additional Language", "IsiNdebele Home Language", "IsiXhosa First Additional Language", "IsiXhosa Home Language", "IsiZulu First Additional Language", "IsiZulu Home Language", "Life Orientation", "Life Sciences", "Mathematical Literacy", "Mathematics", "Physical Sciences", "Religion Studies", "Sepedi First Additional Language", "Sepedi Home Language", "Sesotho First Additional Language", "Sesotho Home Language", "Setswana First Additional Language", "Setswana Home Language", "SiSwati First Additional Language", "SiSwati Home Language", "Tshivenda First Additional Language", "Tshivenda Home Language", "Xitsonga First Additional Language", "Xitsonga Home Language" }));
        getContentPane().add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 710, 650, 60));

        jtxtn7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 710, 190, 60));

        jtxtN7.setEditable(false);
        jtxtN7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtN7ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 710, 190, 60));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\paras\\Downloads\\icons8-calculate-96.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 800, 140, 110));

        jtxtaps10.setEditable(false);
        jtxtaps10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtaps10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 230, 190, 60));

        jtxtaps13.setEditable(false);
        jtxtaps13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtaps13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 470, 190, 60));

        jtxtaps12.setEditable(false);
        jtxtaps12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtaps12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 390, 190, 60));

        jtxtaps14.setEditable(false);
        jtxtaps14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtaps14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 550, 190, 60));

        jtxtaps16.setEditable(false);
        jtxtaps16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtaps16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 710, 190, 60));

        jtxtaps15.setEditable(false);
        jtxtaps15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jtxtaps15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 630, 190, 60));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 910, 120, 90));

        jtxttotal.setEditable(false);
        jtxttotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxttotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jtxttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 810, 190, 60));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Total APS Score");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 810, 430, 60));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Calculate");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1030, 140, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\paras\\Downloads\\icons8-arrow-96.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 920, -1, 110));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("APS Calculator");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 800, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtn3ActionPerformed

    private void jtxtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtn6ActionPerformed

    private void jtxtN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtN2ActionPerformed

    private void jtxtN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtN7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtN7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        op = "calculate";
        
        //1ST ROW
        num1 = Integer.parseInt(jtxtn1.getText());//Converts the mark of the student from a string to an integer
        if(num1>=80 && num1<=100){//Checks if whether the mark entered is between 8 and 100
            jtxtN1.setText("A");//If the mark is between 80 and 100 the Grade will be set to 'A'
            jtxtaps10.setText("7");//If the mark is between 80 and 100 the aps score will be set to 7.
            //The above comments also apply to the code below up until the '7TH ROW' comment Heading
        }
        if(num1>=70 && num1<=79){
            jtxtN1.setText("B");
            jtxtaps10.setText("6");
        }
        if(num1>=60 && num1<=69){
            jtxtN1.setText("C");
            jtxtaps10.setText("5");
        }
        if(num1>=50 && num1<=59){
            jtxtN1.setText("D");
            jtxtaps10.setText("4");
        }
        if(num1>=40 && num1<=49){
            jtxtN1.setText("E");
            jtxtaps10.setText("3");
        }
        if(num1>=30 && num1<=39){
            jtxtN1.setText("F");
            jtxtaps10.setText("2");
        }
        if(num1>=0 && num1<=29){
            jtxtN1.setText("G");
            jtxtaps10.setText("1");
            //2ND ROW-------------------
        }
        num2 = Integer.parseInt(jtxtn2.getText());
        if(num2>=80 && num2<=100){
            jtxtN2.setText("A");
            jtxtaps11.setText("7");
        }
        if(num2>=70 && num2<=79){
            jtxtN2.setText("B");
            jtxtaps11.setText("6");
        }
        if(num2>=60 && num2<=69){
            jtxtN2.setText("C");
            jtxtaps11.setText("5");
        }
        if(num2>=50 && num2<=59){
            jtxtN2.setText("D");
            jtxtaps11.setText("4");
        }
        if(num2>=40 && num2<=49){
            jtxtN2.setText("E");
            jtxtaps11.setText("3");
        }
        if(num2>=30 && num2<=39){
            jtxtN2.setText("F");
            jtxtaps11.setText("2");
        }
        if(num2>=0 && num2<=29){
            jtxtN2.setText("G");
            jtxtaps11.setText("1");
        }
        //3RD ROW-----------------
        num3 = Integer.parseInt(jtxtn3.getText());
        if(num3>=80 && num3<=100){
            jtxtN3.setText("A");
            jtxtaps12.setText("7");
        }
        if(num3>=70 && num3<=79){
            jtxtN3.setText("B");
            jtxtaps12.setText("6");
        }
        if(num3>=60 && num3<=69){
            jtxtN3.setText("C");
            jtxtaps12.setText("5");
        }
        if(num3>=50 && num3<=59){
            jtxtN3.setText("D");
            jtxtaps12.setText("4");
        }
        if(num3>=40 && num3<=49){
            jtxtN3.setText("E");
            jtxtaps12.setText("3");
        }
        if(num3>=30 && num3<=39){
            jtxtN3.setText("F");
            jtxtaps12.setText("2");
        }
        if(num3>=0 && num3<=29){
            jtxtN3.setText("G");
            jtxtaps12.setText("1");
        }
        //4TH ROW----------
        num4 = Integer.parseInt(jtxtn4.getText());
        if(num4>=80 && num4<=100){
            jtxtN4.setText("A");
            jtxtaps13.setText("7");
        }
        if(num4>=70 && num4<=79){
            jtxtN4.setText("B");
            jtxtaps13.setText("6");
        }
        if(num4>=60 && num4<=69){
            jtxtN4.setText("C");
            jtxtaps13.setText("5");
        }
        if(num4>=50 && num4<=59){
            jtxtN4.setText("D");
            jtxtaps13.setText("4");
        }
        if(num4>=40 && num4<=49){
            jtxtN4.setText("E");
            jtxtaps13.setText("3");
        }
        if(num4>=30 && num4<=39){
            jtxtN4.setText("F");
            jtxtaps13.setText("2");
        }
        if(num4>=0 && num4<=29){
            jtxtN4.setText("G");
            jtxtaps13.setText("1");
        }
        //5th ROW
        num5 = Integer.parseInt(jtxtn5.getText());
        if(num5>=80 && num5<=100){
            jtxtN5.setText("A");
            jtxtaps14.setText("7");
        }
        if(num5>=70 && num5<=79){
            jtxtN5.setText("B");
            jtxtaps14.setText("6");
        }
        if(num5>=60 && num5<=69){
            jtxtN5.setText("C");
            jtxtaps14.setText("5");
        }
        if(num5>=50 && num5<=59){
            jtxtN5.setText("D");
            jtxtaps14.setText("4");
        }
        if(num5>=40 && num5<=49){
            jtxtN5.setText("E");
            jtxtaps14.setText("3");
        }
        if(num5>=30 && num5<=39){
            jtxtN5.setText("F");
            jtxtaps14.setText("2");
        }
        if(num5>=0 && num5<=29){
            jtxtN5.setText("G");
            jtxtaps14.setText("1");
        }
        //6TH ROW
        num6 =Integer.parseInt(jtxtn6.getText());
        if(num6>=80 && num6<=100){
            jtxtN6.setText("A");
            jtxtaps15.setText("7");
        }
        if(num6>=70 && num6<=79){
            jtxtN6.setText("B");
            jtxtaps15.setText("6");
        }
        if(num6>=60 && num6<=69){
            jtxtN6.setText("C");
            jtxtaps15.setText("5");
        }
        if(num6>=50 && num6<=59){
            jtxtN6.setText("D");
            jtxtaps15.setText("4");
        }
        if(num6>=40 && num6<=49){
            jtxtN6.setText("E");
            jtxtaps15.setText("3");
        }
        if(num6>=30 && num6<=39){
            jtxtN6.setText("F");
            jtxtaps15.setText("2");
        }
        if(num6>=0 && num6<=29){
            jtxtN6.setText("G");
            jtxtaps15.setText("1");
        }
        //7TH ROW-----------------
        
        num7 = Integer.parseInt(jtxtn7.getText());
        if(num7>=80 && num7<=100){
            jtxtN7.setText("A");
            jtxtaps16.setText("7");
        }
        if(num7>=70 && num7<=79){
            jtxtN7.setText("B");
            jtxtaps16.setText("6");
        }
        if(num7>=60 && num7<=69){
            jtxtN7.setText("C");
            jtxtaps16.setText("5");
        }
        if(num7>=50 && num7<=59){
            jtxtN7.setText("D");
            jtxtaps16.setText("4");
        }
        if(num7>=40 && num7<=49){
            jtxtN7.setText("E");
            jtxtaps16.setText("3");
        }
        if(num7>=30 && num7<=39){
            jtxtN7.setText("F");
            jtxtaps16.setText("2");
        }
        if(num7>=0 && num7<=29){
            jtxtN7.setText("G");
            jtxtaps16.setText("1");
        }
        int ans1, ans2, ans3, ans4, ans5, ans6, ans7;//Initializes ans1 to ans7 as integers
        int total;
        ans1 = Integer.parseInt(jtxtaps10.getText());//Gets the aps value and converts it to type 'int'
        ans2 = Integer.parseInt(jtxtaps11.getText());//Gets the aps value and converts it to type 'int'
        ans3 = Integer.parseInt(jtxtaps12.getText());//Gets the aps value and converts it to type 'int'
        ans4 = Integer.parseInt(jtxtaps13.getText());//Gets the aps value and converts it to type 'int'
        ans5 = Integer.parseInt(jtxtaps14.getText());//Gets the aps value and converts it to type 'int'
        ans6 = Integer.parseInt(jtxtaps15.getText());//Gets the aps value and converts it to type 'int'
        ans7 = Integer.parseInt(jtxtaps16.getText());//Gets the aps value and converts it to type 'int'
        total = ans1+ans2+ans3+ans4+ans5+ans6+ans7;//Calculates the total aps score by adding all the aps scores of all the subjects
        jtxttotal.setText(""+total);//Displays the total aps score in the totals text field.
        
        
        
        
        
       
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        op = "clear";//names the 'clear' button as clear
        if(op == "clear"){//If the 'clear' button is clicked, the following code inside the if statement will be executed
            jtxtn1.setText("");//Empty's out the text field
            jtxtn2.setText("");//Empty's out the text field
            jtxtn3.setText("");//Empty's out the text field
            jtxtn4.setText("");//Empty's out the text field
            jtxtn5.setText("");//Empty's out the text field
            jtxtn6.setText("");//Empty's out the text field
            jtxtn7.setText("");//Empty's out the text field
            jtxtN1.setText("");//Empty's out the text field
            jtxtN2.setText("");//Empty's out the text field
            jtxtN3.setText("");//Empty's out the text field
            jtxtN4.setText("");//Empty's out the text field
            jtxtN5.setText("");//Empty's out the text field
            jtxtN6.setText("");//Empty's out the text field
            jtxtN7.setText("");//Empty's out the text field
            jtxtaps10.setText("");//Empty's out the text field
            jtxtaps11.setText("");//Empty's out the text field
            jtxtaps12.setText("");//Empty's out the text field
            jtxtaps13.setText("");//Empty's out the text field
            jtxtaps14.setText("");//Empty's out the text field
            jtxtaps15.setText("");//Empty's out the text field
            jtxtaps16.setText("");//Empty's out the text field
            jtxttotal.setText("");//Empty's out the text field
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradingCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradingCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradingCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradingCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradingCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jtxtN1;
    private javax.swing.JTextField jtxtN2;
    private javax.swing.JTextField jtxtN3;
    private javax.swing.JTextField jtxtN4;
    private javax.swing.JTextField jtxtN5;
    private javax.swing.JTextField jtxtN6;
    private javax.swing.JTextField jtxtN7;
    private javax.swing.JTextField jtxtaps10;
    private javax.swing.JTextField jtxtaps11;
    private javax.swing.JTextField jtxtaps12;
    private javax.swing.JTextField jtxtaps13;
    private javax.swing.JTextField jtxtaps14;
    private javax.swing.JTextField jtxtaps15;
    private javax.swing.JTextField jtxtaps16;
    private javax.swing.JTextField jtxtn1;
    private javax.swing.JTextField jtxtn2;
    private javax.swing.JTextField jtxtn3;
    private javax.swing.JTextField jtxtn4;
    private javax.swing.JTextField jtxtn5;
    private javax.swing.JTextField jtxtn6;
    private javax.swing.JTextField jtxtn7;
    private javax.swing.JTextField jtxttotal;
    // End of variables declaration//GEN-END:variables
}
